### ISSUE TITLE
Revamp the `conda build` process to use the `requirements.txt`

### ISSUE THREAD

**Issue by roomrys** [talmolab/sleap#1195]
# Bug description
Revamp the `conda build` process to use the `requirements.txt` instead of having to re-list all `pip` dependencies in `build.bat` and `bld.sh`

## Expected behaviour

The `pip` requirements that are kept track of in one place (`requirements.txt`) would be used instead of having to relist these requirements in two other places (increasing the likelihood of a failed build).

## Actual behaviour
We currently relist `pip` requirements as part of our build process.

## Suggestion
At the very least, we could automate the creation of the `build.bat` and `bld.sh` files IF after scouring the internet and reading the `conda build` docs we do not find what we are looking for.

**Comment by talmo** [comment]
For context, [this has been an issue since 2019](https://github.com/talmolab/sleap/blame/1c75ab82f4f08fcaa42b5de54a43ad169b296116/.conda/bld.bat#L5).

I think part of the reason we went with this workaround and haven't touched it is because it was hard to troubleshoot it since we didn't have local environments that replicate GitHub Actions Runners (e.g., a Docker image that executes a workflow YAML). Maybe that's changed since 2019?

Side note: Packages installed via `pip` within the conda build process will get included in the final build artifact!! This means that if we have TensorFlow, OpenCV or PySide2 installed via `pip`, the resulting package will be 100s of MB. As a workaround since some of these didn't have first party-supported conda packages for the right versions/OSes, we made a dumb wrapper around the PyPI wheels and separated them into [conda packages in our own channel](https://github.com/talmolab/conda_packages). This doesn't really resolve the problem but it at least makes SLEAP conda builds <200 MB. If we could get rid of the rest of the `pip` deps we could probably get that down to just a few MB.
