### ISSUE TITLE
Exporting CSV file but doesn't include predictions and instance score

### ISSUE THREAD

**Issue by msjindal** [talmolab/sleap#1681]
# Bug description

When exporting the project as a csv file the file does not include the predicted frames, only the user labeled frames

## Expected behaviour

When exporting the csv after predictions, the file should include the predicted frames and their instance score, instead, it doesn't have instance scores, and it only has the user labeled frames.

## Your personal set up

- OS:

- Version(s):

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)
  - [ ] [Conda from source](https://sleap.ai/installation.html#conda-from-source)
  - [ ] [pip package](https://sleap.ai/installation.html#pip-package)
  - [ ] [Apple Silicon Macs](https://sleap.ai/installation.html#apple-silicon-macs)

<details><summary>Environment packages</summary>

```
# paste output of `pip freeze` or `conda list` here
```

</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```

</details>

**Comment by glinnes12** [comment]
Hi,
I believe I have the same issue as msjindal and a result receive error messages when importing tracking data into SimBA: the predictions seem to be needed, as well as a link of the video file within the SLP data? Could it perhaps also be an error because the predictions are saved separately from the user-labelled frames?

I tried to export the my SLEAP predictions in H5, SLP or CSV files but none of them seem to work with SimBA (they give me different error messages), so I was wondering whether perhaps some of the information is lost when saving the data from SLEAP. But of course it could also be an error on the side of SimBA...

I am very new to all of these things, so I hope what I am writing makes sense 😅
Any help/tips would be very much appreciated :) Thank you!

**Comment by eberrigan** [comment]
Hi @msjindal,

I tried to reproduce this error but I was able to generate a csv that include both user instances and predictions with instance scores:

![Image](https://github.com/talmolab/sleap/assets/106755962/110f58ae-42fc-4b87-a7a6-9834b1a7b002)


Do you mind providing a bit more info on your setup, like the SLEAP version you're using? If you don't mind sharing the .SLP file that produces this error, we can do more troubleshooting.

---

@glinnes12: Do you mind creating a new discussion or issue for your problem if you haven't gotten help from the simba side yet?

Thanks!

Elizabeth

**Comment by talmo** [comment]
This seems to have been resolved over in https://github.com/sgoldenlab/simba/issues/294, but feel free to open a new issue or discussion if needed :)
