### ISSUE TITLE
Issue Opening SLEAP Project

### ISSUE THREAD

**Issue by justinecorsilia** [talmolab/sleap#1903]
# Bug description

I have an exported SLEAP training package with a .slp file inside that I have added videos to and labeled additional instances. However, when I try to re-open this file using SLEAP, nothing opens, and I get this error: 

<img width="1410" alt="Screenshot 2024-08-14 at 5 43 56 AM" src="https://github.com/user-attachments/assets/a4dcc1dd-703a-45a0-9e1a-0b7b6e7744bb">
<img width="861" alt="Screenshot 2024-08-14 at 5 44 04 AM" src="https://github.com/user-attachments/assets/ffea977a-da6a-4697-95ce-2118e7638ed3">

I am using SLEAP version 1.3.1, and when I attempt to open the file with version 1.3.3 the same issue occurs

**Comment by talmo** [comment]
Hi @justinecorsilia,

Thanks for sharing the error logs!

It looks like there's an issue with reading an embedded HDF5 video, which is likely related to a training package. Note that SLP files with embedded images aren't intended to be further labeled/edited, so if that's the case let us know and we can recommend alternatives to the workflow.

Some next steps:

1. Let us know what steps you took to generate this SLP file so we can diagnose how the error might have come about.
2. Consider [sharing the problematic SLP file](https://forms.gle/d3eftG7mu1ooZbo18) with us so we can take a peek into its contents to see what's going on.
3. Have you tried this since updating to v1.3.3 following #1906?

Cheers,

Talmo

**Comment by justinecorsilia** [comment]
Hi Talmo,
Thank you so much. I created a training package using the top down model. I realized after training that I needed to label more frames, but instead of adding them to the initial file, I added videos and labeled frames to the .slp file inside the package folder. Once I did that, I was no longer able to open the file. I shared the file using the link you provided as well.
Thanks again

**Comment by justinecorsilia** [comment]
Hi Talmo,
I just wanted to reach out and see if there are any updates on this? 
Thanks again
-Justine

**Comment by talmo** [comment]
Hi @justinecorsilia,

Super sorry about the delay!! I totally missed this earlier when you replied 😓 

Right, the issue here is related to adding new labels to a .pkg.slp file. These package files aren't really intended for continued labeling, so what you want to do is to go back to the original labels that you exported it from and add your labels there.

You can still import predictions created from running inference on the .pkg.slp file (e.g., suggestions) and SLEAP will merge them to the original labels files appropriately.

Let me know if that makes sense, doesn't work for you, or if you have any questions!

Cheers,

Talmo
