### ISSUE TITLE
GLIBC_2.14 dependency

### ISSUE THREAD

**Issue by nachonacho2** [talmolab/sleap#1916]
# Bug description
Unable to use SLEAP (e.g. python -c "import sleap; sleap.versions()") on HPC due to dependency on GLIBC_2.14, specifically getting error:
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found

On a second attempt at installing, can not even install:
The following package could not be installed
└─ sleap 1.3.3**  is not installable because it requires
   └─ cudnn 8.2.1.* , which requires
      └─ __glibc >=2.17,<3.0.a0 , which is missing on the system.

Is it possible to loosen these requirements? We are unable to update GLIBC on this system.

## Your personal set up
- OS: Centos 6.9, which is using 'GLIBC_2.12'.

- Version(s): SLEAP v1.3.3

- SLEAP installation method (listed [here](https://sleap.ai/installation.html#)):
  - [ ] [Conda from package](https://sleap.ai/installation.html#conda-package)

**Comment by eberrigan** [comment]
Hi @nachonacho2, 

How are you installing SLEAP? 

The SLEAP [conda package](https://github.com/talmolab/sleap/blob/develop/.conda/meta.yaml) has very specific requirements since these versions of `cudnn`, `cuda-toolkit`, `cuda-nvcc`, `tensorflow`, `numpy` and `sleap` have been tested to work correctly together alogrithmicaly and when interacting with the GPU. That does not mean there are not other versions of the cuda and NVIDIA dependencies that could work, but it is difficult to figure this out. 

You can install the dependencies you need for your HPC and then install `sleap` using the PyPI package. Directions are [here](https://sleap.ai/installation.html#pip-package).

Best,

Elizabeth

**Comment by eberrigan** [comment]
It seems like [miniforge3](https://github.com/conda-forge/miniforge?tab=readme-ov-file#miniforge3) needs `glibc>=2.17` for Linux OS. I would try to update your HPC since this is an important piece of software for managing packages and environments (not just for sleap).

**Comment by nachonacho2** [comment]
Thanks Elizabeth! Unfortunately the decision whether to update the HPC is out of my hands. I'm sure other researchers will run into similar problems soon enough. I've requested the system be updated but I think I'm stuck until it happens.

**Comment by nachonacho2** [comment]
Just to update, we managed to work around the glibc issue but loading an updated module. Unfortunately, we then ran into the problem that SLEAP uses CUDA 11, which doesn't work on CentOS6. I'll just revert to using colab for this project for now.
