### ISSUE TITLE
CSV output - Instance Scores

### ISSUE THREAD

**Issue by msjindal03** [talmolab/sleap#2024]
I was hoping to gain some clarity on exactly what the node instance scores measure and what the goal number is to aim for. Is the overall instance score the average of all the nodes' instance scores? Is the instance score basically a prediction score?

**Comment by gitttt-1234** [comment]
Hi @msjindal03,

Yes, it's essentially a predicted score for each instance. There are 2 scores associated with an instance in a predicted `.slp` file: `point_scores` and `instance_score`. Each node in an instance has a `point_score`, which is the peak value in the output confidence map of that particular node and represents the confidence with which the node is detected by the model. The instance scores are associated with the instance as a whole; it represents the confidence with which the instance is predicted (typically, in a centroid model, the instance score is the value of the centroid peak in the output confidence map. In a bottom-up model, the confidence score is from the part affinity field and for single-instance model, it's the sum of confidences of individual nodes confidence scores.). 

Hope this helps, let me know if you have any further questions.

Thanks!

Divya

**Comment by gitttt-1234** [comment]
Hi @msjindal03 ,

Yes for the first few epochs, the model is still trying to learn the features and hence, results in lower confidence scores. After certain epochs (depending on model/ data), the model would be confident enough to predict the nodes. And, the reason why the confidence scores aren't bound to1 is because these scores aren't normalized. This discussion #1323 provides more details on how the confidence scores are computed for each model.

Let me know if there are any other questions!

Thanks,

Divya
