### ISSUE TITLE
Add documentation for creating Conda environment "no_cuda" / older Macs

### ISSUE THREAD

**Issue by pollytur** [talmolab/sleap#705]
Hello!
I tried to install sleep on Mac (Intel i7, Monterey 12.2.1, no GPU) via Conda but it failed

```
$ conda env create -f environment.yml -n sleap
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - cudatoolkit=11.3.1
  - nvidia::cuda-nvcc=11.3
  - cudnn=8.2.1
```

I used  `git clone https://github.com/murthylab/sleap && cd sleap` and `conda env create -f environment.yml -n sleap` before as `conda create -y -n sleap -c sleap -c nvidia -c conda-forge sleap=1.2.2` does not work for mac.
Seems like, indeed, there are no these packages for a laptop without GPU. I wanted to landmark the videos on my usual laptop and then to train on a server with a GPU. Could you please let me know if there is such an option? And if yes, how should I solve the thing above? (I already tried` conda install -c conda-forge <package_name=version>` and it did not help)

Thanks in advance!
Polly

**Comment by pollytur** [comment]
I also tried to run the following
1. `conda activate sleap_trial`
2.  `pip3 install sleap`
3.  `sleap-label`

But it failed with the following:
(sleap_trial) $ sleap-label
```
Traceback (most recent call last):
  File "/usr/local/bin/sleap-label", line 5, in <module>
    from sleap.gui.app import main
  File "/usr/local/lib/python3.9/site-packages/sleap/__init__.py", line 9, in <module>
    from sleap.io.dataset import Labels, load_file
  File "/usr/local/lib/python3.9/site-packages/sleap/io/dataset.py", line 80, in <module>
    from sleap.gui.dialogs.missingfiles import MissingFilesDialog
  File "/usr/local/lib/python3.9/site-packages/sleap/gui/dialogs/missingfiles.py", line 154, in <module>
    class MissingFileTable(QtWidgets.QTableView):
TypeError: 'Shiboken.ObjectType' object is not iterable
```

**Comment by roomrys** [comment]
Hi @pollytur,

Thanks for bringing this to our attention. In response to **conda from source** installation error, since you are not training on your own computer, we can try removing the CUDA libraries from the dependencies. Can you try editing the `environment.yml` file in the main (outer) `sleap` directory. Remove or comment out the following lines under `dependencies:`
```
    - cudatoolkit=11.3.1
    - cudnn=8.2.1
    - nvidia::cuda-nvcc=11.3
```
Then, from within the main (outer) `sleap` directory, run the `conda env create -f environment.yml -n sleap` command again. I am trying it out as well on my end to ensure that nothing else breaks when we do this (however I am on Windows). Let me know how that works for you.

Thanks,
Liezl

**Comment by pollytur** [comment]
Thank you! 
Seems like this works. I will let you know if I will find any suspicious behaviour. 

Thank you one more time,
Polly

**Comment by roomrys** [comment]
Perfect! We will work on a more permanent fix, but glad to get you up and running.

**Comment by roomrys** [comment]
I added a note in the [conda from source installation](https://sleap.ai/installation.html#conda-from-source) where we specify to use the environment_no_cuda.yml if the user's computer does not have a NVIDIA GPU.
