### ISSUE TITLE
Tracking and Proofreading Documentation Outdated

### ISSUE THREAD

**Issue by sunmart** [talmolab/sleap#714]
**Problem:** The documentation on tracking, proofreading (https://sleap.ai/develop/guides/proofreading.html) and others need to be updated to reflect newer features.

- Inference pipeline tracking options (see screenshot below)
- Add documentation for "Propagate Track Labels"
- Link hotkey references ([like this](https://sleap.ai/develop/guides/proofreading.html#:~:text=time%20using%20the-,down%20arrow,-key.%20It%E2%80%99s%20usually)) out to [GUI guide page](https://sleap.ai/guides/gui.html) so hotkey documentation all lives in a single place.

----

_Original issue:_

Hi,

Is there any way to specify that there are no more than 2 animals in a video to help with tracking the animal's identity? I read the tracking and proofreading section of the document, but I'm not entirely sure what this means or how to implement it - 

"Finally, you have an option second-pass method which “cleans” the resulting identities. To use this method, you specify a target number of tracks (i.e., how many animals there are in your video). SLEAP then goes frame by frame and removes instances over this target number."

Thanks for all your help!

**Comment by roomrys** [comment]
Hi @sunmart,

Yes, there is! From the SLEAP GUI, if you navigate to the Inference Pipeline via Predict >> Inference, you will need to:

1. Specify the **Tracker (cross-frame identity) Method**
2. Uncheck the **No target** checkbox
3. Specify the **Target Number of Instances Per Frame**
4. Check the **Cull to Target Instance Count** checkbox

![image](https://user-images.githubusercontent.com/38435167/165585851-37f4667a-2d3b-4d5f-a5bd-3536ba2fc8dd.png)

Let me know if this helps,
Liezl

**Comment by sunmart** [comment]
Thanks for the quick response, Liezl! I just tried this, and while it helps with the number of instances on a given frame, it still doesn't solve the problem where it switches the identity of the animal over time. I'm working with B6 mice, is there a particular set of parameters (instance vs iou/ greedy vs Hungarian) you would recommend to optimize this?

**Comment by roomrys** [comment]
Hi @sunmart,

The **Hungarian** matching should help in solving the switching of identities as it maximizes the similarities over the entire track of the animal vs the **greedy** matching which chooses identities based on only the current frame's similarity scores.

For the similarity method, this depends on how your animals (B6 mice in this case) are moving through out the video. E.g., if the designated centroids of the mice continuously overlap throughout the video, then using **centroid** or **iou** may not be great since the centroids of different mice will be very close to each other and likely indistinguishable. In this case, we would need more information/points to distinguish the mice and therefore the **instance** similarity method may be a better choice.

Even after finding the parameters that optimize tracking for your dataset, identity switches may still occur, but we are able to fix those with [proofreading](https://sleap.ai/develop/guides/proofreading.html#id1).

I assume you have already seen the [page on tracking](https://sleap.ai/develop/guides/proofreading.html) since you quoted it in the original post, but just linking it here for reference. 

Hope this helped! Please let me know which parameters worked best for your data and/or if you have further questions.

Thanks,
Liezl

**Comment by sunmart** [comment]
Hi Liezl,

I've been trying to proofread, and every time I correct the identity on a frame and try to "ctrl+E" to the next identity switch, it just takes me to the next frame (600 to 601 for ex). The proofreading page says that once you correct an identity switch it should apply it to all subsequent frames with that track, so do you have to save the correction each time or retrain a model so the subsequent frames will be labeled with the correct track?

Thanks for all your help!!

**Comment by roomrys** [comment]
Hi @sunmart,

You do not have to save the correction each time or retrain the model for subsequent frames to be added to the correct track.

The "ctrl + E" command will take you to the next frame that has a new track spawned (new identity). We can determine if there are any new tracks by taking a look at the scrollbar below the displayed frame. If there is a new unique color, then there is a new track spawned.

Note that when you correct the identities through proofreading, the tracks will be switched only from the current frame onwards (no tracks in previous frames will be affected). Thus, we should start proofreading at the beginning of the video and move towards the end of the video.

I feel I may not have been of much help as I was unable to replicate the problem on my end. If you are still having trouble, do you mind sending a screen-share/video of the problem?

Thanks,
Liezl

**Comment by sunmart** [comment]
Hi Liezl,
I think I figured it out. I needed to toggle "Propogate track Labels" on for it to work the way you said it should.

**Comment by roomrys** [comment]
Yikes, it seems we are missing documentation on that. I apologize for not being able to help, but thank you very much for coming back with the solution! Adding this as a TODO.

**Comment by sunmart** [comment]
No worries! Since we're already discussing this, the proofreading page also says that in order to jump 50 frames at a time, you need to press the down arrow, but that hasn't been working for me. I wonder if that is a Windows/MAC difference? (We use a Windows system)

**Comment by roomrys** [comment]
Hi @sunmart,

Also another documentation issue.... The down arrow key was previously the keyboard shortcut used  for "Frame Next Large Step" - the default is currently set to `Ctrl+Alt+Right`, but is able to be changed through Help > Keyboard Shortcuts. Expect a website update in the future, until then please keep pointing these things out.

**Comment by roomrys** [comment]
The tracking docs have been updated! #761 #775
